export const restaurants = [
  {
    id: "r1",
    coverPhoto: '/public/images/Coffeemania-large.jpg',
    name: "Coffee Mania",
    dess: "Coffee & Wine bar",
    price: 5,
    delivery: 9,
    type: "Coffee",
    img: "/public/images/restaurants/coffee-mania.png",
    address: 'Lotfi Zadeh Technology Center, Caspian Plaza, Jafar Jabbarli, 44 17th floor, Baku 1065',
    products: [
      {
        id: "c1",
        name: "Americano 200 ml",
        price: 2.5,
        quantity: 1,
        desc: "Caffè Americano is a type of coffee drink prepared by diluting an espresso with hot water.",
        img: "/public/images/restaurants/coffee-names.webp",
      },
      {
        id: "c2",
        name: "Latte 200 ml",
        price: 4.5,
        quantity: 1,
        desc: "Caffè latte often shortened to just latte in English, is a coffee drink of Italian origin made with espresso and steamed milk.",
        img: "/public/images/restaurants/coffee-names.webp",
      },

      {
        id: "c3",
        name: "Hot Chocolate 200 ml",
        price: 3.5,
        quantity: 1,
        desc: "Hot chocolate, also known as hot cocoa or drinking chocolate, is heated chocolate milk.",
        img: "/public/images/restaurants/coffee-names.webp",
      },

      {
        id: "c4",
        name: "CAFFÈ MOCHA 200 ml",
        price: 4.5,
        quantity: 1,
        desc: "A caffè mocha also called mocaccino is a chocolate-flavoured warm beverage that is a variant of a café latte commonly served in a glass rather than a mug.",
        img: "/public/images/restaurants/coffee-names.webp",
      },

      {
        id: "c5",
        name: "ESPRESSO  200 ml",
        price: 5.5,
        quantity: 1,
        desc: "Espresso is both a coffee beverage and a brewing method. It is not a specific bean, bean blend, or roast level.",
        img: "/public/images/restaurants/coffee-names.webp",
      },
    ],
  },
  {
    id: "r2",
    coverPhoto: "../public/images/burger-king-large.svg.png",
    name: "Burger King",
    dess: "BURGERS WITH CHICKEN AND FISH",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/burgur-king.svg",
    address: 'Fuzuli street, Azadliq prospekti, Baku',
    products: [
      {
        id: "b1",
        name: "Qrill Chicken Barbekyu",
        price: 6.9,
        quantity: 1,
        desc: "In this sandwich, grilled tender white chicken fillet is found, barbecue sauce, leaf lettuce, ripe tomato, thick mayonnaise and crispy fried onions on a toasted bun.",
        img: "../public/images/restaurants/qrill-chicken.avif",
      },
      {
        id: "b2",
        name: "Chessy Mary",
        price: 7.2,
        quantity: 1,
        desc: "Grilled chicken in combination with Cheddar cheese and Parmesan cheese, crispy onions, fresh vegetables and peerless Caesar dressing. Lots and lots of cheese!",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "b3",
        name: "Whopper Melt",
        price: 9.3,
        quantity: 1,
        desc: "The new Whopper Melt from Burger King® features two slices of toast, layered with ¼. lb of flame-grilled beef, melty American cheese, caramelized onions and stacker sauce.",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "b4",
        name: "Chicken Nuggets",
        price: 11.2,
        quantity: 1,
        desc: "Made with white meat, our bite-sized Chicken Nuggets are tender and juicy on the inside and crispy on the outside. Coated in a homestyle seasoned",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "b5",
        name: "Sandwich",
        price: 7.5,
        quantity: 1,
        desc: "A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread, or more generally any dish wherein bread serves as a container or wrapper for another food type",
        img: "../public/images/restaurants/chessy-mary.avif",
      },
    ],
  },
  {
    id: "r3",
    coverPhoto: '../public/images/mcdonalds-large.jpg',
    name: "Mc Donalds",
    dess: "McDonald's: Burgers, Fries & More. Quality Ingredients.",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/mc-dolands.png",
    address: '28 Mall, Azadlyg avenue',

    products: [
      {
        id: "m1",
        name: "Hamburger",
        price: 6.9,
        quantity: 1,
        desc: "In this sandwich, grilled tender white chicken fillet is found, barbecue sauce, leaf lettuce, ripe tomato, thick mayonnaise and crispy fried onions on a toasted bun.",
        img: "https://mcdonalds.az/images/39a475f7ca35d52af7ea94751ee7ccc1.png",
      },
      {
        id: "m2",
        name: "Cheeseburger",
        price: 7.2,
        quantity: 1,
        desc: "Grilled chicken in combination with Cheddar cheese and Parmesan cheese, crispy onions, fresh vegetables and peerless Caesar dressing. Lots and lots of cheese!",
        img: "https://mcdonalds.az/images/06f60bc8898a8bf0f8455beca0106fd0.png",
      },

      {
        id: "m3",
        name: "Double Big Mac",
        price: 9.3,
        quantity: 1,
        desc: "The new Whopper Melt from Burger King® features two slices of toast, layered with ¼. lb of flame-grilled beef, melty American cheese, caramelized onions and stacker sauce.",
        img: "https://mcdonalds.az/images/63ecfcc842755085bf3ac6f89a72e230.png",
      },

      {
        id: "b4",
        name: "Big Tasty",
        price: 11.2,
        quantity: 1,
        desc: "Made with white meat, our bite-sized Chicken Nuggets are tender and juicy on the inside and crispy on the outside. Coated in a homestyle seasoned",
        img: "https://mcdonalds.az/images/78abcdfef00a8090642d30cbe579cdff.jpg",
      },

      {
        id: "b5",
        name: "Mangal(Beef)",
        price: 7.5,
        quantity: 1,
        desc: "A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread, or more generally any dish wherein bread serves as a container or wrapper for another food type",
        img: "https://mcdonalds.az/images/fe7e33d176752c3e23af79dd4044f9b6.jpg",
      },
    ],
  },
  {
    id: "r4",
    coverPhoto: '/public/images/maharaja-large.webp',
    name: "Maharaja",
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Indian Food",
    img: "../public/images/restaurants/maharaja.jpg",
    address: '59 Gara Garayev avenue, Baku',

    products: [
      {
        id: "ma1",
        name: "Hamburger",
        price: 6.9,
        quantity: 1,
        desc: "In this sandwich, grilled tender white chicken fillet is found, barbecue sauce, leaf lettuce, ripe tomato, thick mayonnaise and crispy fried onions on a toasted bun.",
        img: "../public/images/restaurants/qrill-chicken.avif",
      },
      {
        id: "ma2",
        name: "Cheeseburger",
        price: 7.2,
        quantity: 1,
        desc: "Grilled chicken in combination with Cheddar cheese and Parmesan cheese, crispy onions, fresh vegetables and peerless Caesar dressing. Lots and lots of cheese!",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "ma3",
        name: "Double Big Mac",
        price: 9.3,
        quantity: 1,
        desc: "The new Whopper Melt from Burger King® features two slices of toast, layered with ¼. lb of flame-grilled beef, melty American cheese, caramelized onions and stacker sauce.",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "ma4",
        name: "Big Tasty",
        price: 11.2,
        quantity: 1,
        desc: "Made with white meat, our bite-sized Chicken Nuggets are tender and juicy on the inside and crispy on the outside. Coated in a homestyle seasoned",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "ma5",
        name: "Mangal(Beef)",
        price: 7.5,
        quantity: 1,
        desc: "A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread, or more generally any dish wherein bread serves as a container or wrapper for another food type",
        img: "../public/images/restaurants/chessy-mary.avif",
      },
    ],
  },
  {
    id: "r5",
    coverPhoto: '/public/images/dera-large.jpg',
    name: "Dera Restaurant",
    dess: "Classic, long-running fast-food chain known for its burgers & fries.",
    price: 5,
    delivery: 9,
    type: "Indian Food",
    img: "../public/images/restaurants/dera.jpg",
    address: 'Ataturk avenue',

    products: [
      {
        id: "de1",
        name: "Hamburger",
        price: 6.9,
        quantity: 1,
        desc: "In this sandwich, grilled tender white chicken fillet is found, barbecue sauce, leaf lettuce, ripe tomato, thick mayonnaise and crispy fried onions on a toasted bun.",
        img: "../public/images/restaurants/qrill-chicken.avif",
      },
      {
        id: "de2",
        name: "Cheeseburger",
        price: 7.2,
        quantity: 1,
        desc: "Grilled chicken in combination with Cheddar cheese and Parmesan cheese, crispy onions, fresh vegetables and peerless Caesar dressing. Lots and lots of cheese!",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "de3",
        name: "Double Big Mac",
        price: 9.3,
        quantity: 1,
        desc: "The new Whopper Melt from Burger King® features two slices of toast, layered with ¼. lb of flame-grilled beef, melty American cheese, caramelized onions and stacker sauce.",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "de4",
        name: "Big Tasty",
        price: 11.2,
        quantity: 1,
        desc: "Made with white meat, our bite-sized Chicken Nuggets are tender and juicy on the inside and crispy on the outside. Coated in a homestyle seasoned",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "de5",
        name: "Mangal(Beef)",
        price: 7.5,
        quantity: 1,
        desc: "A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread, or more generally any dish wherein bread serves as a container or wrapper for another food type",
        img: "../public/images/restaurants/chessy-mary.avif",
      },
    ],
  },
  {
    id: "r6",
    name: "Hong Kong",
    coverPhoto: '/public/images/hongkong-large.jpg',
    dess: "chinese, sea-food, thai, lebanese, caribbean",
    price: 5,
    delivery: 9,
    type: "Chinese Food",
    img: "../public/images/restaurants/hong-kong.jpg",
    address: '1959 Tabriz St, Baku',

    products: [
      {
        id: "ho1",
        name: "Hamburger",
        price: 6.9,
        quantity: 1,
        desc: "In this sandwich, grilled tender white chicken fillet is found, barbecue sauce, leaf lettuce, ripe tomato, thick mayonnaise and crispy fried onions on a toasted bun.",
        img: "../public/images/restaurants/qrill-chicken.avif",
      },
      {
        id: "ho2",
        name: "Cheeseburger",
        price: 7.2,
        quantity: 1,
        desc: "Grilled chicken in combination with Cheddar cheese and Parmesan cheese, crispy onions, fresh vegetables and peerless Caesar dressing. Lots and lots of cheese!",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "ho3",
        name: "Double Big Mac",
        price: 9.3,
        quantity: 1,
        desc: "The new Whopper Melt from Burger King® features two slices of toast, layered with ¼. lb of flame-grilled beef, melty American cheese, caramelized onions and stacker sauce.",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "ho4",
        name: "Big Tasty",
        price: 11.2,
        quantity: 1,
        desc: "Made with white meat, our bite-sized Chicken Nuggets are tender and juicy on the inside and crispy on the outside. Coated in a homestyle seasoned",
        img: "../public/images/restaurants/chessy-mary.avif",
      },

      {
        id: "ho5",
        name: "Mangal(Beef)",
        price: 7.5,
        quantity: 1,
        desc: "A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread, or more generally any dish wherein bread serves as a container or wrapper for another food type",
        img: "../public/images/restaurants/chessy-mary.avif",
      },
    ],
  },
  {
    id: "r7",
    coverPhoto: '/public/images/papajohns-large.svg',
    name: "Papa Johns",
    dess: "Pizza take-out & delivery chain offering classic & specialty pizzas, plus wings, sides & desserts.",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/papa-johns.svg",
    address: '106 A Nizami St, Baku 1005',

    products: [
      {
        id: "pa1",
        name: "American Hot",
        price: 6.9,
        quantity: 1,
        desc: "Tomato Sauce, Mozzarella, Pepperoni and Jalapeno peppers",
        img: "https://www.papajohns.az/uploads/images/pizza/american-hot.png",
      },
      {
        id: "pa2",
        name: "Spicy Chicken Ranch",
        price: 7.2,
        quantity: 1,
        desc: "Ranch Sauce, Grilled Chicken, Mushrooms, Garlic, Jalapeno Peppers, Tomatoes, and Mozzarella",
        img: "https://www.papajohns.az/uploads/images/pizza/Spicy-chicken-ranch.png",
      },

      {
        id: "pa3",
        name: "Cheddar Chicken Club",
        price: 9.3,
        quantity: 1,
        desc: "Grilled Chicken, Tomatoes, Ranch Sauce, Mozzarella, Cheddar, Ham",
        img: "https://www.papajohns.az/uploads/images/pizza/Cheddar-%C3%87iken-Club.png",
      },

      {
        id: "pa4",
        name: "Mexican",
        price: 11.2,
        quantity: 1,
        desc: "Grilled Chicken, Tomatoes, Fresh Mushrooms, Green Peppers, Jalapeno Peppers, Mozzarella",
        img: "https://www.papajohns.az/uploads/images/meksika.jpg",
      },

      {
        id: "pa5",
        name: "Classic Pepperoni",
        price: 7.5,
        quantity: 1,
        desc: "Pepperoni, Extra Mozzarella",
        img: "https://www.papajohns.az/uploads/images/klassik_pepperoni.jpg",
      },
    ],
  },
  {
    id: "r8",
    coverPhoto: '/public/images/dominos-large.png',
    name: "Dominos",
    dess: "Delivery/carryout chain offering a wide range of pizzas & a variety of other dishes & sides",
    price: 5,
    delivery: 9,
    type: "Fast Food",
    img: "../public/images/restaurants/dominos.png",
    address: '34 S, Qara Qarayev prospekti, Baku',

    products: [
      {
        id: "do1",
        name: "CHICKEN KICKERS",
        price: 6.9,
        quantity: 1,
        desc: "200 g pieces of Chicken breast in Crispy coating Baked in Oven + 100g Potato Wedges + Domino's Yogurt sauce",
        img: "https://www.papajohns.az/uploads/images/Papadias/%C4%B0talyan-papadias.png",
      },
      {
        id: "do2",
        name: "CHICKEN WINGS",
        price: 7.2,
        quantity: 1,
        desc: "6 pcs of Marinated Chicken Wings Baked in Oven + 100g Potato Wedges + Domino's Mexican sauce",
        img: "https://www.papajohns.az/uploads/images/Papadias/Acili-%C3%A7iken-ran%C3%A7-papadias.png",
      },

      {
        id: "do3",
        name: "CRISPY CHICKEN POPS",
        price: 9.3,
        quantity: 1,
        desc: "100 g of Spicy Chicken Balls Baked in Oven",
        img: "https://www.papajohns.az/uploads/images/Papadias/%C3%87iken-BBQ-Papadias.png",
      },

      {
        id: "do4",
        name: "POTATO WEDGES",
        price: 11.2,
        quantity: 1,
        desc: "Oven Baked Potato Wedges + Ketchup",
        img: "https://www.papajohns.az/uploads/images/pendirli_cubuqlar.jpg",
      },

      {
        id: "do5",
        name: "Classic Pepperoni",
        price: 7.5,
        quantity: 1,
        desc: "Pepperoni, Extra Mozzarella",
        img: "https://www.papajohns.az/uploads/images/toyuq_qanadlari.jpg",
      },
    ],
  },
];
